#!/bin/bash
# 20-configure-apt
#
# This script configure apt
#

info " Starting: Configure APT "

#
# Setup the sources.list file for new installations of Debian GNU/Linux.
#

# disable apt sources.list base
sed -i 's/^deb/#deb/' /etc/apt/sources.list

# erase all .list repositories
rm -f /etc/apt/sources.list.d/*.list

# generate new repositories
if [ "$REPO_TYPE" == "local" ]; then
	mirror="file://$REPO_URL/debian/"
else
	mirror="http://$REPO_URL/debian/"
fi

# oficial repositories
cat <<E_O_APT > /etc/apt/sources.list.d/$SUITE.list
# oficial
deb $mirror $SUITE $REPO_SECTIONS
E_O_APT

# backport repositories
cat <<E_O_APT > /etc/apt/sources.list.d/backports.list
deb $mirror $SUITE-backports $REPO_SECTIONS
E_O_APT

if [ "$APT_SECURITY" == "yes" ]; then
# security and update repositories
cat <<E_O_APT > /etc/apt/sources.list.d/security.list
# updates
deb $mirror $SUITE-updates main
# security
deb http://security.debian.org/ $SUITE/updates main
E_O_APT
fi

cat <<EOF > /etc/apt/apt.conf.d/80-update
Acquire::Check-Valid-Until "false";
EOF

cat <<EOF > /etc/apt/apt.conf.d/10-Debian
Acquire::Language "none";
Acquire::PDiffs  "false";
APT::Install-Recommends  "false";
APT::Get::AutomaticRemove  "true";
APT::Clean-Installed  "true";
EOF

cat <<EOF > /etc/apt/preferences.d/$SUITE.pref
Package: *
Pin: release n=$SUITE
Pin-Priority: 300

Package: *
Pin: release n=$SUITE-backports
Pin-Priority: 250

Package: *
Pin: release o=Unofficial Multimedia Packages
Pin-Priority: 250

EOF

#
#  Now that the sources have been setup make sure the system is up to date.
#
debug "updating APT database"
$APT update

# install keyring list
debug "Install Debian keyrings"
aptitude -y -t wheezy install $KEYRINGS

# upgrade system
debug "upgrade system"
$APT -y --force-yes install apt
$APT upgrade

# install tools
install_package initramfs-tools firmware-linux firmware-linux-free

# update and upgrade system
$APT upgrade -y
aptitude -y full-upgrade

# install test
if [ -z $(which lsb_release) ]; then
	echo "arepalinux warning: lsb-release is required"
	$APT -y install lsb-release
fi
