#!/bin/bash
# 03-change-grub

info "Update GRUB options"

options=`cat /etc/default/grub | grep madvise`

# aplicar cambios al grub solo si no estan aplicados
if [ -z "$options" ]; then
	$SED -i -e "s/GRUB_CMDLINE_LINUX=\"\"/GRUB_CMDLINE_LINUX=\"${GRUB_FLAGS}\"/" /etc/default/grub
fi

# disable ipv6
#if [ "$DISABLE_IPV6" == "yes" ]; then
#if [ -z "`grep 'ipv6' /etc/default/grub`" ]; then
	# disable ipv6
#	sed -i -e "s/GRUB_CMDLINE_LINUX=\"\(.*\)\"/GRUB_CMDLINE_LINUX=\"\1 ipv6.disable=1\"/" /etc/default/grub
#fi
#fi

debug "Update grub configuration"

# update grub
/usr/sbin/update-grub
