#!/bin/bash
# 02-configure-sysctl
#
# configure sysctl
#

if [ "$ENABLE_FORWARDING" == 'yes' ]; then
	CHANGES=$(grep "^net.ipv4.ip_forward" /etc/sysctl.conf | tail)
	if [ -z "$CHANGES" ]; then
cat <<EOF >> /etc/sysctl.conf

# enable ipv4 forwarding (only virtual servers)
net.ipv4.ip_forward = 1

EOF
	fi
fi

if [ "$DISABLE_IPV6" == 'yes' ]; then
	CHANGES=$(grep "^net.ipv6.conf.all.disable_ipv6" /etc/sysctl.conf | tail)
	if [ -z "$CHANGES" ]; then
cat <<EOF >> /etc/sysctl.conf

# disable ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

EOF
	fi
fi

CHANGES=$(egrep "vm.vfs_cache_pressure" /etc/sysctl.conf | tail)
if [ -z "$CHANGES" ]; then

info "Apply sysctl changes"

# apply patches to sysctl
cat <<EOF >> /etc/sysctl.conf
# sysctl config

# tcp memory
net.core.optmem_max = 40960
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.core.wmem_default = 2097152
net.core.wmem_max = 16777216
net.core.rmem_max = 16777216
net.core.rmem_default = 2097152
net.core.wmem_default = 2097152
# If your servers talk UDP, also up these limits
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192

##enable window scaling
net.ipv4.tcp_window_scaling = 1
##
net.ipv4.tcp_no_metrics_save = 1

# ipv4 settings
net.ipv4.tcp_rfc1337 = 1

# TCP congestion control (cubic, htcp, vegas)
net.ipv4.tcp_congestion_control = htcp

# Make room for more TIME_WAIT sockets due to more clients,
# and allow them to be reused if we run out of sockets
# Also increase the max packet backlog
net.core.netdev_max_backlog = 50000
net.ipv4.tcp_max_syn_backlog = 30000
net.ipv4.tcp_max_tw_buckets = 2000000
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_synack_retries = 1

# Disable TCP slow start on idle connections
net.ipv4.tcp_slow_start_after_idle = 0

##  tcp selective acknowledgements. 
net.ipv4.tcp_sack = 1
net.ipv4.tcp_fack = 0

net.ipv4.tcp_mtu_probing=1
net.ipv4.tcp_orphan_retries = 1
net.ipv4.tcp_max_orphans = 8192
net.ipv4.tcp_keepalive_time = 1800
net.ipv4.tcp_keepalive_intvl = 30

# increase socket listen backlog
net.core.somaxconn = 32400
# number of packets to keep in backlog before the kernel starts dropping them
net.ipv4.tcp_max_syn_backlog = 32400

# netfilter settings
net.netfilter.nf_conntrack_acct = 1
net.netfilter.nf_conntrack_generic_timeout = 15
net.netfilter.nf_conntrack_icmp_timeout = 5
net.netfilter.nf_conntrack_tcp_timeout_close = 15
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30
net.netfilter.nf_conntrack_tcp_timeout_last_ack = 30
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 30
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 30
net.netfilter.nf_conntrack_tcp_timeout_established = 1800
net.netfilter.nf_conntrack_tcp_timeout_syn_recv = 15
net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 15
net.netfilter.nf_conntrack_udp_timeout = 10
net.netfilter.nf_conntrack_udp_timeout_stream = 10
net.netfilter.nf_conntrack_max = 2621440

# VM
vm.dirty_ratio = 20
vm.dirty_background_ratio = 20
vm.dirty_bytes = 67108864
vm.dirty_background_bytes = 134217728
vm.mmap_min_addr = 4096

# swapping
vm.swappiness = 0
vm.vfs_cache_pressure = 20

# fs
fs.aio-max-nr = 1048576
fs.file-max = 287573

# memory
kernel.sem = 250 256000 100 1024
kernel.shmall = 536870912
kernel.shmmax = 1073741824
kernel.shmmni = 8192
kernel.msgmnb = 65536
kernel.msgmax = 65536
#threads
kernel.threads-max = 126015

# kernel
kernel.core_uses_pid = 1
kernel.sysrq = 0
kernel.kptr_restrict = 1

# security
# ipv4 security
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.tcp_timestamps = 0
net.ipv4.conf.all.proxy_arp = 0
net.ipv4.conf.default.proxy_arp = 0
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0

# Increase ephermeral IP ports
net.ipv4.ip_local_port_range = 25000 65000

# enable cgroup
# enable cgroup auto-scheduler
kernel.sched_autogroup_enabled = 1
kernel.sched_rt_runtime_us = 950000

# Scheduler-Tuning
kernel.sched_latency_ns = 5000000
kernel.sched_min_granularity_ns = 100000
kernel.sched_wakeup_granularity_ns = 100000

EOF

# enable cgroup on fstab
cat <<EOF >> /etc/fstab

# cgroups
cgroup  /sys/fs/cgroup  cgroup  defaults  0   0

EOF
fi
