#!/bin/bash
# 06-optimize-system
#
# optimize disk, network and other utilities
#

# Agregar rc.local

info "Optimize System"

cat <<EOF > /etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# optimizacion del disco
/bin/bash /sbin/optimicedisk.sh
exit 0
EOF
chmod a+x /etc/rc.local

cat <<EOF > /sbin/compartir_internet
#!/bin/bash
iptables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT
iptables -P FORWARD ACCEPT
EOF
chmod a+x /sbin/compartir_internet

# optimize disk settings
install_package hdparm

cp files/optimicedisk.sh /sbin/optimicedisk.sh
chmod a+x /sbin/optimicedisk.sh

# network
cp files/pre-eth0.sh /sbin/pre-eth0.sh
chmod a+x /sbin/pre-eth0.sh

# increase tcp congestion window
cp files/eth0.sh /sbin/eth0.sh
chmod a+x /sbin/eth0.sh

# configure limits
cat <<EOF > /etc/security/limits.d/stack.conf
# nofile
root               soft    nofile            131072
root               hard    nofile            131072
*               soft    nofile            131072
*               hard    nofile            131072
# stack
root            soft    stack            16384
root            hard    stack            16384
*               soft    stack            16384
*               hard    stack            16384
EOF

# disable core dumps
if [ -z "`grep 'ulimit -S' /etc/profile`" ]; then
	echo 'ulimit -S -c 0 > /dev/null 2>&1' >> /etc/profile
	echo "*	hard 		core 		0" >> /etc/security/limits.conf
fi
