#!/bin/bash -e
# 11-install-software
# install all basic software required
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

info " Installing basic software and utilities "

$APT -y install sudo locate rsync bash-completion wget tcpdump ntpdate finger links lynx less screen tree curl wget telnet iputils-ping dnsutils lsof patch irqbalance acpi-support lvm2 powermgmt-base

# disable exim4
aptitude -y purge exim4 exim4-daemon-light

# configure postfix for local system
install_package postfix

if [ -z "`grep 'inet_protocols' /etc/postfix/main.cf`" ]; then
	echo 'inet_protocols = ipv4' >> /etc/postfix/main.cf
fi
sed -i -e "s/smtpd_banner.*$/smtpd_banner = $SERVERNAME ESMTP $DOMAIN/" /etc/postfix/main.cf
