#!/bin/bash -e
# 11-install-software
# install all basic software required
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

info " Install basic software and utilities "

$APT -y install sudo locate rsync bash-completion wget ntp tcpdump ntpdate finger links lynx ethtool less screen tree curl wget telnet iputils-ping dnsutils lsof

if [[ "$MODE" = "workstation" || "$MODE" = "desktop" ]]; then
	install_package laptop-detect
	if [ -z "$(laptop-detect)"]; then
		# We're a laptop/Notebook
		install_package laptop-mode-tools task-laptop xorg-driver-synaptics
	fi
	# install basic Xorg
	install_package xserver-xorg-core xserver-xorg xorg xserver-xorg-input-kbd xserver-xorg-input-evdev xserver-xorg-input-mouse
fi

if [ "$MODE" == "server" ]; then
# configure NTP
hwclock --systohc
service ntp restart

# disable exim4
aptitude -y purge exim4 exim4-daemon-light
# configure postfix for local system
install_package postfix

if [ -z "`grep 'inet_protocols' /etc/postfix/main.cf`" ]; then
	echo 'inet_protocols = ipv4' >> /etc/postfix/main.cf
fi
sed -i -e "s/smtpd_banner.*$/smtpd_banner = $SERVERNAME ESMTP $DOMAIN/" /etc/postfix/main.cf
fi
