#!/bin/bash
# 20-firewall
#
#  Install and configure Shorewall firewall
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

info " install and configure shoreline Firewall "

install_package shorewall

# enable shorewall
sed -i -e "s/startup=0/startup=1/" /etc/default/shorewall

if [ "$DISABLE_IPV6" == 'yes' ]; then
# - deshabilitar ipv6
sed -i "s/^DISABLE_IPV6=.*$/DISABLE_IPV6=Yes/" /etc/shorewall/shorewall.conf
fi
# optimize shorewall rules
sed -i "s/^OPTIMIZE=.*$/OPTIMIZE=8/" /etc/shorewall/shorewall.conf
# - integrate with fail2ban
sed -i "s/^BLACKLISTNEWONLY=.*$/BLACKLISTNEWONLY=No/" /etc/shorewall/shorewall.conf

# - habilitar ip-forwarding:
if [ "$ENABLE_FORWARDING" == 'yes' ]; then
sed -i "s/^IP_FORWARDING=.*$/IP_FORWARDING=On/" /etc/shorewall/shorewall.conf
cat > /etc/shorewall/masq << EOF
############################################################################
# Shorewall Masq
#INTERFACE    SUBNET
$BRIDGENAME       172.16.30.0/24
EOF
# Esto permite que la red LAN salga a Internet de manera directa y enmascarada (Forward masquerading)
fi

if [[ "$MODE" = "workstation" || "$MODE" = "desktop" ]]; then
firstiface=$(ip route | grep default |  awk '{ print $5}' | tr -d ' ')
# configure shorewall
cat > /etc/shorewall/interfaces << EOF
############################################################################
# Shorewall interfaces
FORMAT 2
#ZONE   INTERFACE   OPTIONS
lan     lan0             routefilter,routeback,bridge,tcpflags,nosmurfs,logmartians,sourceroute=0
net     $firstiface        routefilter,tcpflags,nosmurfs,sourceroute=0
EOF
else
# shorewall interfaces
cat > /etc/shorewall/interfaces << EOF
############################################################################
# Shorewall interfaces
FORMAT 2
#ZONE   INTERFACE   OPTIONS
lan     lan0             routefilter,routeback,bridge,tcpflags,nosmurfs,logmartians,sourceroute=0
net     $BRIDGENAME        routefilter,bridge,tcpflags,nosmurfs,sourceroute=0
EOF
fi

# common files

# zones
cat > /etc/shorewall/zones << EOF
############################################################################
# Shorewall Zones
#ZONE   TYPE    OPTIONS         IN          OUT
#                   OPTIONS         OPTIONS
fw  firewall
net ipv4
lan ipv4
EOF
# policies
cat > /etc/shorewall/policy << EOF
############################################################################
# shorewall policies
#SOURCE     DEST        POLICY      LOG LEVEL   LIMIT:BURST
fw      lan     ACCEPT
fw     net     ACCEPT
# acceso desde lan
lan     fw      ACCEPT
lan     net     ACCEPT
# acceso desde internet
net     fw      DROP
net     lan     DROP
# The FOLLOWING POLICY MUST BE LAST
all     all     DROP      info
EOF
# and rules
sshport=$(cat /etc/ssh/sshd_config | grep Port | cut -d ' ' -f2)
cat > /etc/shorewall/rules << EOF
#ACTION     SOURCE  DEST    PROTO   DEST   SOURCE  ORIGINAL RATE   USER/  MARK
#                                   PORT   PORT(S) DEST     LIMIT  GROUP
#
# Accept Ping and Traceroute from the internet
ACCEPT:info net     fw     icmp       8
# Accept NTP udp
ACCEPT    net     fw    udp     123
# SSH Access
ACCEPT      all     fw     tcp        $sshport    -    -   2/min:3
# Accept PING
Ping(ACCEPT)     net     all
EOF
