#!/bin/bash
# 30-security
#
#  Ensure all security software (fail2ban, psad, rkhunter) is installed and configured
#  in this system
#

# Don't allow any nut to kill the server
perl -npe 's/ca::ctrlaltdel:\/sbin\/shutdown/#ca::ctrlaltdel:\/sbin\/shutdown/' -i /etc/inittab

# Passwords expire every 180 days
perl -npe 's/PASS_MAX_DAYS\s+99999/PASS_MAX_DAYS 180/' -i /etc/login.defs

# Passwords may only be changed once a day
perl -npe 's/PASS_MIN_DAYS\s+0/PASS_MIN_DAYS 1/g' -i /etc/login.defs

# Login retries change to 6
perl -npe 's/LOGIN_RETRIES\s+5/LOGIN_RETRIES 6/g' -i /etc/login.defs

# kick off idle users:
message "Idle users will be removed after 15 minutes"
cat <<EOF > /etc/profile.d/os-security.sh
# set a 15 min timeout policy for bash shell
readonly TMOUT=900
export TMOUT
EOF
chmod +x /etc/profile.d/os-security.sh

# install fail2ban
install_package fail2ban

sed -i 's/^banaction.*$/banaction = shorewall/' /etc/fail2ban/jail.conf
sed -i 's/^destemail.*$/destemail = $MAIL/' /etc/fail2ban/jail.conf
sed -i 's/^bantime.*$/bantime = 1200/' /etc/fail2ban/jail.conf

service fail2ban restart

# install denyhosts
install_package denyhosts

sed -i -e 's/^PURGE_DENY.*$/PURGE_DENY = 72h/' /etc/denyhosts.conf
sed -i -e 's/^ADMIN_EMAIL.*$/ADMIN_EMAIL = $MAIL/' /etc/denyhosts.conf
sed -i -e 's/^#RESET_ON_SUCCESS.*$/RESET_ON_SUCCESS = yes/' /etc/denyhosts.conf
sed -i -e 's/^#SYSLOG_REPORT=YES.*$/SYSLOG_REPORT=YES/' /etc/denyhosts.conf
sed -i -e 's/^#SYNC_SERVER.*$/SYNC_SERVER = http:\/\/xmlrpc.denyhosts.net:9911/' /etc/denyhosts.conf

service denyhosts restart

# install psad
install_package psad

sed -i 's/^EMAIL_ADDRESSES.*$/EMAIL_ADDRESSES             ${MAIL};/' /etc/psad/psad.conf
sed -i "s/^HOSTNAME.*$/HOSTNAME             ${NAME};/" /etc/psad/psad.conf
sed -i 's/^ENABLE_IPV6_DETECTION.*$/ENABLE_IPV6_DETECTION             NO;/' /etc/psad/psad.conf
sed -i 's/^FW_MSG_SEARCH.*$/FW_MSG_SEARCH               DROP;\nFW_MSG_SEARCH               Shorewall:net2all:DROP:;\nFW_MSG_SEARCH Shorewall:net2fw:DROP:;/' /etc/psad/psad.conf

# install rootkit tools
install_package chkrootkit rkhunter
