#!/bin/bash
# 50-configure-locales
#
# install and configure locales
#

info " Configuring Linux locales "

#
#  Install locales
#
install_package locales
install_package util-linux-locales

#
# define locales
#

# en_US.UTF-8
L=$( echo "$CLANG"_"$COUNTRY"."$ENCODING")
# en_US:en
L2=$( echo "$CLANG"_"$COUNTRY":"$CLANG")

export LANG=$L
export LANGUAGE=$L2

/usr/sbin/update-locale LANG=$CLANG LANGUAGE=$L2

# generate locale file
cat <<EOF > /etc/locale.gen
$L $ENCODING
EOF

# regenerate locales
/usr/sbin/locale-gen
