#!/bin/bash -e
# 10-configure-dns
#
# configure a dns cache (dnsmasq)
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

if [ "$DISABLE_DNSCACHE" != 'yes' ]; then

info " Install dns cache (dnsmasq) "

if [ -z "`which dnsmasq`" ]; then
# install dnsmasq
install_package dnsmasq

groupadd -r dnsmasq
adduser dnsmasq dnsmasq

# Guardas el archivo original
cp /etc/dnsmasq.conf /etc/dnsmasq.conf.orig

sed -i 's/^#port.*$/port=53/' /etc/dnsmasq.conf
sed -i 's/^#domain-needed/domain-needed/' /etc/dnsmasq.conf
sed -i 's/^#bogus-priv/bogus-priv/' /etc/dnsmasq.conf
sed -i 's/^#resolv-file=.*$/resolv-file=\/etc\/resolv.dnsmasq/' /etc/dnsmasq.conf
sed -i 's/^#bogus-priv/bogus-priv/' /etc/dnsmasq.conf
sed -i 's/^#resolv-file=.*$/resolv-file=\/etc\/resolv.dnsmasq/' /etc/dnsmasq.conf

# configure user and group
sed -i 's/^#user=.*$/user=dnsmasq/' /etc/dnsmasq.conf
sed -i 's/^#group=.*$/group=dnsmasq/' /etc/dnsmasq.conf

cat <<EOF > /etc/dnsmasq.d/local.conf
dns-forward-max=150
cache-size=1000
neg-ttl=3600
EOF
chown dnsmasq.dnsmasq /etc/dnsmasq.d -R

# generate a resolv.dnsmasq
cat <<EOF > /etc/resolv.dnsmasq
search $DOMAIN
# nameservers
nameserver 8.8.8.8
EOF
chown dnsmasq.dnsmasq /etc/resolv.dnsmasq

# generate a resolv.conf
cat <<EOF > /etc/resolv.conf
search $DOMAIN
nameserver 127.0.0.1
# fallback DNS
nameserver 8.8.8.8
EOF
# securing resolv.conf
chattr +i /etc/resolv.conf
# TODO: configurar resolvconf

# enable config dir
cat <<EOF >> /etc/dnsmasq.conf
# Include another lot of configuration options.
#conf-file=/etc/dnsmasq.more.conf
conf-dir=/etc/dnsmasq.d 
EOF



fi # which dnsmasq
fi # enable dns-cache
