#!/bin/bash
# 20-firewall
#
#  Install and configure Shorewall firewall
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

info " install and configure shoreline Firewall "

install_package shorewall

# enable shorewall
sed -i -e "s/startup=0/startup=1/" /etc/default/shorewall

# first enabled interface
firstiface=$(ip addr show | grep "UP," | grep "MULTICAST" | awk '{ print $2}' | cut -d':' -f1)
netmask=$(get_netmask $firstiface)
ip=$(get_ip $firstiface)
network=$(get_network $ip $netmask)
octet=$(get_subnet $firstiface)
subnet="$network/$octet"

# configure shorewall
cat > /etc/shorewall/interfaces << EOF
############################################################################
# Shorewall interfaces
FORMAT 2
#ZONE   INTERFACE   OPTIONS
loc     lan0             routefilter,tcpflags,bridge,nosmurfs,logmartians,sourceroute=0
-     $firstiface        routefilter,tcpflags,nosmurfs,sourceroute=0
EOF
# loc es un bridge, conectado a los LXC containers
# net es la interfaz que nos conecta a Internet (ej: bridge de la eth0)
# lan es la red interna de la interfaz que nos conecta a Internet

cat > /etc/shorewall/zones << EOF
############################################################################
# Shorewall Zones
#ZONE   TYPE    OPTIONS         IN          OUT
#                   OPTIONS         OPTIONS
fw  firewall
net ipv4
lan ipv4
loc ipv4
EOF

cat > /etc/shorewall/hosts << EOF
############################################################################
# Shorewall Hosts
#ZONE	IFACE:SUBNET
lan	$firstiface:$subnet
net	$firstiface:0.0.0.0/0
EOF


cat > /etc/shorewall/masq << EOF
############################################################################
# Shorewall Masq
#INTERFACE    SUBNET
$firstiface       172.16.30.0/24
EOF
# Esto permite que la red LAN salga a Internet de manera directa y enmascarada (Forward masquerading)

cat > /etc/shorewall/policy << EOF
############################################################################
# shorewall policies
#SOURCE     DEST        POLICY      LOG LEVEL   LIMIT:BURST
fw      lan     ACCEPT
fw     net     ACCEPT
# acceso desde lan
lan     fw      ACCEPT
lan     net     ACCEPT
# acceso desde internet
net     fw      DROP
net     lan     DROP
# The FOLLOWING POLICY MUST BE LAST
all     all     DROP      info
EOF

sshport=$(cat /etc/ssh/sshd_config | grep Port | cut -d ' ' -f2)

cat > /etc/shorewall/rules << EOF
#ACTION     SOURCE  DEST    PROTO   DEST   SOURCE  ORIGINAL RATE   USER/  MARK
#                                   PORT   PORT(S) DEST     LIMIT  GROUP
#
# Accept Ping and Traceroute from the internet
ACCEPT:info net     fw     icmp       8
# Accept NTP udp
ACCEPT    net     fw    udp     123
# Acceso SSH
ACCEPT      all     fw     tcp        $sshport    -    -   2/min:3
# Aceptar PING
Ping(ACCEPT)     net     all
EOF

# - deshabilitar ipv6
sed -i "s/^DISABLE_IPV6=.*$/DISABLE_IPV6=Yes/" /etc/shorewall/shorewall.conf

# - integrate with fail2ban
sed -i "s/^BLACKLISTNEWONLY=.*$/BLACKLISTNEWONLY=No/" /etc/shorewall/shorewall.conf

# - habilitar ip-forwarding:
sed -i "s/^IP_FORWARDING=.*$/IP_FORWARDING=On/" /etc/shorewall/shorewall.conf
sed -i "s/^OPTIMIZE=.*$/OPTIMIZE=8/" /etc/shorewall/shorewall.conf
