#!/bin/bash
# 90-selinux
#
# Install basic functionality of selinux
#
#

if [ "$DISABLE_SELINUX" != 'yes' ]; then

info " Installing Audit Daemon "

# install acct (account information)
install_package acct

service acct stop
mkdir /var/account
sed -i 's/\/var\/log\/account\/pacct/\/var\/account\/pacct/' /etc/init.d/acct
mv /var/log/account/pacct /var/account/
chown -R root.adm /var/account
service acct start

# install auditd (audit information)
install_package auditd audispd-plugins

# insert basic audit rules
if [ -z "`grep 'faillog' /etc/audit/audit.rules`" ]; then
cat <<EOF >> /etc/audit/audit.rules
# registrar los intentos fallidos de lectura sobre archivos
-a exit,always -F arch=b64 -S open -F success=0 
# registrar los intentos fallidos de escritura sobre archivos
-a exit,always -F arch=b64 -S write -F success=0 
-w /etc/sudoers -p wa -k sudoers-change
-w /var/log/faillog -p wa -k logins
-w /var/log/lastlog -p wa -k logins
-A exit,always -F arch=b64 -F euid=0 -F uid!=0 -S execve
EOF
fi

info " Installing SELinux "

install_package selinux-basics selinux-utils selinux-policy-default
status=$(sestatus | grep "SELinux status" | awk '{ print $2}')
if [ "$status" != 'enabled' ]; then
# enable selinux
selinux-activate
# enable filesystem check on boot
sed -i 's/^#FSCKFIX=no/FSCKFIX=yes/' /etc/default/rcS
warning "SELinux is enabled, please restart system"
fi

# generate basic policies
audit2allow -a -M mypolicies
# enable this policies
semodule -i mypolicies.pp
# enable user
semanage login -a -s staff_u $SUPPORT
semanage user -a -R 'staff_r sysadm_r' $SUPPORT

fi
