#!/bin/bash
# 95-upgrade-kernel
#
# This script configure apt
#

if [ "$MODE" = "desktop" ]; then
	if [ "$ENABLE_BACKPORTS" == "yes" ]; then
	# upgrade kernel from backports
		# install kernel kbuild for backports
		aptitude -y -t $SUITE-backports install $(aptitude -t $SUITE-backports search -F "%p" -O version linux-kbuild | tail -n1)
		aptitude -y -t $SUITE-backports install initramfs-tools
		# latest RT_PREEMPT Kernel from backports:
		aptitude -y -t $SUITE-backports --with-recommends install $(aptitude -t $SUITE-backports search -F "%p" -O version,name linux-image | grep -F "rt" | grep -Fv "dbg" | tail -n1) $(aptitude -t $SUITE-backports search -F "%p" -O version,name linux-headers | grep -F "rt" | grep -Fv "dbg" | tail -n1)
		# install latest firmware
		aptitude -y -t $SUITE-backports --without-recommends install firmware-linux-nonfree firmware-linux-free $(aptitude -t $SUITE-backports search firmware- | grep "^i " | awk '{ print $2}')
	else
		# upgrade to latest kernel
		aptitude -y -t $SUITE --with-recommends install $(aptitude -t $SUITE search -F "%p" -O version linux-image | grep -Fv "\-dbg" | tail -n1) $(aptitude -t $SUITE search -F "%p" -O version linux-headers | grep -Fv "\-dbg" | tail -n1)
	fi
fi
