#!/bin/bash
# 96-install-utilities
#
#  This script install and configure vim, bashrc, profile and other utilities in the
#  installation.
#

info " Configure utilities "

# install and configure vim
install_package vim vim-scripts

## configure vim
cp files/vimrc.local /etc/vim/vimrc.local

# install and configure bash_completion
install_package bash-completion

## enable bash-completion
sed -i '/#if ! shopt.*$/,+6s/#//' /etc/bash.bashrc

# configure bash.bashrc
## configure bashrc
sed -i 's/^#force_color_prompt=.*$/force_color_prompt=yes/' /etc/skel/.bashrc
# enable colors in bash
sed -i "s/^# export LS_OPTIONS=.*$/export LS_OPTIONS='--color=auto'/" /root/.bashrc
sed -i '/^# eval "`dircolors`"/eval "`dircolors`"/' /root/.bashrc
sed -i '/# alias ls.*$/,+3s/# //' /root/.bashrc

if [ -z "`grep 'history options' /etc/bash.bashrc`" ]; then
cat <<EOF >> /etc/bash.bashrc
# history options
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000
# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac
force_color_prompt=yes
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias egrep='egrep --color=auto'
fi
EOF
fi

# configure GIT
install_package git-core
/usr/bin/git config --global user.name "$ACCOUNT"
/usr/bin/git config --global user.email "$MAIL"

# filesystem tools
install_package xfsprogs btrfs-tools dosfstools ntfs-3g cifs-utils

##########################################
#
# basic programming languages
#
install_package ${prefix} perl-modules python-minimal python-pip python-setuptools ruby rubygems php5-cli

# secure php5-cli
sed -i 's/^register_globals \= On/register_globals \= Off/' /etc/php5/cli/php.ini
echo 'register_globals = Off' >> /etc/php5/cli/php.ini
sed -i 's/^expose_php \= On/expose_php \= Off/' /etc/php5/cli/php.ini
sed -i 's/^allow_url_fopen \= On/allow_url_fopen \= Off/' /etc/php5/cli/php.ini
sed -i 's/^zlib.output_compression \= Off/zlib.output_compression \= On/' /etc/php5/cli/php.ini

##########################################
#
# bash prompt features
#
if [ -z "`grep '^PS1=' /etc/bash.bashrc`" ]; then
cat <<EOF >> /etc/bash.bashrc
# bash color prompt
if [ "$force_color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '                                                       
fi
unset color_prompt force_color_prompt
EOF
fi
if [ -z "`grep '^PS1=' /root/.bashrc`" ]; then
# color prompt for root
#echo "PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\# '" >> /root/.bashrc
echo "PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u\[\033[01;32m\]@\[\033[1;33m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]# '" >> /root/.bashrc
fi
