#!/bin/bash -e
# 98-configure-users
#
# configure system user account
#

info "Configure Users"

install_package libpam-cracklib libpam-mkhomedir

# crear grupo y usuario de $SUPPORT
/usr/sbin/groupadd --gid 1100 $SUPPORT
/usr/sbin/useradd --uid 1100 --create-home -d /home/$SUPPORT -s /bin/bash -g $SUPPORT $SUPPORT

info "User '$SUPPORT' is disabled, please set user password"

# agregar usuario al grupo sudo
adduser $SUPPORT $SUPPORT
adduser $SUPPORT sudo

# expiration password (1 year)
chage -M 365 $SUPPORT
