#!/bin/bash
# 99-cleanup
#
# Basic security and cleanup options
#
#

info " Cleanup System ... "

# cleanup system
install_package localepurge deborphan
$APTITUDE -y purge $(deborphan --libdevel) $(deborphan --find-config)

#
# clean apt cache
$APT -y autoremove
$APT -y clean
$APTITUDE clean
# protect dash and locales
/bin/echo locales hold | /usr/bin/dpkg --set-selections
/bin/echo dash hold | /usr/bin/dpkg --set-selections

#  Remove disable-daemons script (if present)
if [ -x "/usr/sbin/policy-rc.d" ]; then
	rm -f "/usr/sbin/policy-rc.d"
fi
