#!/bin/bash
# 99-cleanup
#
# Basic security and cleanup options
#
#

info " Cleanup System ... "

# cleanup system
install_package localepurge deborphan
$APTITUDE -y purge $(deborphan --libdevel) $(deborphan --find-config)

# remove obsolete packages
$APTITUDE purge ~o

#
# clean apt cache
$APT -y autoremove
$APT -y clean
$APTITUDE clean

#  Remove disable-daemons script (if present)
if [ -x "/usr/sbin/policy-rc.d" ]; then
	rm -f "/usr/sbin/policy-rc.d"
fi
